// Static seed data for Vercel deployment
// This file contains all events as static JSON so the site works without a database
// The admin/submission features will need a Turso DB for production writes
//
// AUDIT NOTES (2026-05-26, scrape → 2026-05-26 weekly vision scrape):
// - Removed: YUSSUR (past, Jan 2026), Playground Toronto (past, Dec 2025),
//   Rubber Sluts: GIMP (no listing found), Leather & Latex Social (fabricated),
//   BDSM 101 Workshop (fabricated), Furry Meetup TO (fabricated),
//   Pride Fetish Ball (fabricated), Underwear Party — Skivvies (fabricated),
//   Rope Bondage 201 (fabricated), Drag Brunch (removed — no drag),
//   Northern Bear Bash (removed — not kink-focused)
// - Corrected: MUZZLED date Jun 26 (verified getmuzzled.ca),
//   BLUF Toronto Pride Jun 27 (verified bluf.com),
//   Impulse May 30 (verified eventbrite),
//   Playground Kink 4.2 Jun 26 (verified yohomo)
// - Added: Pitbull Corruption (Pride Fri Jun 27), Pitbull Utopia (Pride Sat Jun 28)
// - NOTE: Drag events removed per user preference — kink/fetish only
// - 2026-05-26 SCRAPE: Added 11 new events from yohomo.ca, eventbrite
// - 2026-05-26 WEEKLY VISION SCRAPE:
//   Date corrections: Pitbull Corruption Jun 28→Jun 26 (Fri, TicketWeb verified),
//     Pitbull Utopia Jun 29→Jun 27 (Sat, flyer vision verified),
//     Pitbull Bunker Jun 21→Jun 5 (Fri, flyer vision verified)
//   Added 14 new events: BLUF Toronto May 30, KINK 101, JOCKSTRAP, G.L.U.E. Social,
//     L.O.C.K. Chastity Social, Naked Night, D.F.M.O., Erotic Life Drawing,
//     SURRV'D Leather Dark Room, Hot Tease Film Festival, K.I.S.S. Kink/Tantra Salon,
//     fetNOIR Back To School, Mall Goths Goth Dance Party, Pup Pride

export interface Event {
  id: string;
  title: string;
  description: string;
  venue: string;
  address: string;
  start_time: string;
  end_time: string;
  url: string;
  source: string;
  category_slugs: string[];
  recurrence?: string;
  recurrence_label?: string;
  is_recurring?: boolean;
  external_id?: string;
}

export interface Category {
  slug: string;
  name: string;
  emoji: string;
  color: string;
  description: string;
}

export const categories: Category[] = [
  { slug: 'circuit', name: 'Circuit Party', emoji: '🔊', color: '#E11D48', description: 'Circuit parties, dance events, big beats' },
  { slug: 'leather', name: 'Leather', emoji: '🧥', color: '#1E1E1E', description: 'Leather events, leather bars, leather contests' },
  { slug: 'latex', name: 'Latex / Rubber', emoji: '🖤', color: '#0EA5E9', description: 'Latex and rubber events, dress codes' },
  { slug: 'bdsm', name: 'BDSM / Kink', emoji: '⛓️', color: '#7C3AED', description: 'BDSM demos, munches, play parties, workshops' },
  { slug: 'puppy', name: 'Puppy Play', emoji: '🐕', color: '#F59E0B', description: 'Puppy play events, moshes, socials' },
  { slug: 'furry', name: 'Furry', emoji: '🐾', color: '#10B981', description: 'Furry meetups, socials, events' },
  { slug: 'drag', name: 'Drag', emoji: '💄', color: '#EC4899', description: 'Drag shows, drag queen events, drag king nights' },
  { slug: 'bear', name: 'Bear', emoji: '🐻', color: '#92400E', description: 'Bear events, bear socials, bear runs' },
  { slug: 'fetish', name: 'Fetish Night', emoji: '🔥', color: '#DC2626', description: 'General fetish nights, dress-code parties' },
  { slug: 'underwear', name: 'Underwear', emoji: '🩲', color: '#6366F1', description: 'Underwear parties, underwear nights' },
  { slug: 'cruising', name: 'Cruising', emoji: '👀', color: '#059669', description: 'Cruising events, dark rooms, saunas' },
  { slug: 'social', name: 'Social / Mixer', emoji: '🍻', color: '#6B7280', description: 'Social events, meetups, mixers, brunches' },
  { slug: 'workshop', name: 'Workshop / Education', emoji: '📚', color: '#8B5CF6', description: 'Educational workshops, skill-sharing, demos' },
  { slug: 'pride', name: 'Pride', emoji: '🌈', color: '#F43F5E', description: 'Pride events, pride month activities' },
  { slug: 'pet-play', name: 'Pet Play', emoji: '🐾', color: '#D97706', description: 'Pet play, puppy, kitten, pony play events' },
  { slug: 'bluf', name: 'BLUF', emoji: '🔵', color: '#2563EB', description: 'BLUF (Brotherhood of Leather Uniforms) events' },
  { slug: 'goth', name: 'Goth / Dark', emoji: '🦇', color: '#4A0E4E', description: 'Goth, dark alternative, industrial events' },
];

export const events: Event[] = [
  // === VERIFIED RECURRING EVENTS ===
  {
    id: 'bad-dog',
    title: 'Bad Dog',
    description: 'Bad Dog — the legendary pup & handler party at The Black Eagle. Pups, handlers, and dog lovers unite. Dress code: pup gear encouraged. Dark room open.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-06T21:00:00',
    end_time: '2026-06-07T02:00:00',
    url: 'https://www.getmuzzled.ca',
    source: 'getmuzzled.ca',
    category_slugs: ['puppy', 'fetish'],
    recurrence: 'nth-weekday:1-6',
    recurrence_label: 'Every 1st Saturday',
    is_recurring: true,
  },
  {
    id: 'bluf-toronto',
    title: 'BLUF Toronto — Pride Edition',
    description: 'BLUF (Brotherhood of Leather Uniforms) Toronto Leather Social — Pride Edition. Come out in your leather and uniforms to meet fellow BLUF members and other leathermen. No dress code enforced. Open to non-members. No cover.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-27T18:00:00',
    end_time: '2026-06-27T21:00:00',
    url: 'https://www.bluf.com/events/',
    source: 'bluf.com',
    category_slugs: ['leather', 'bluf', 'pride'],
    recurrence: 'nth-weekday:5-6',
    recurrence_label: 'Last Saturday of the month',
    is_recurring: true,
  },
  {
    id: 'muzzled',
    title: 'MUZZLED',
    description: 'MUZZLED is where the party animals go. Queer, kink-friendly, community-focused events. Great music, great vibes, great people. Be unapologetically yourself. Doors 9pm at The Parkdale Hall.',
    venue: 'The Parkdale Hall',
    address: '1605 Queen St E Suite 3, Toronto',
    start_time: '2026-06-26T21:00:00',
    end_time: '2026-06-27T02:00:00',
    url: 'https://www.getmuzzled.ca',
    source: 'getmuzzled.ca',
    category_slugs: ['puppy', 'fetish', 'social'],
    recurrence: 'monthly',
    recurrence_label: 'Monthly (check site)',
    is_recurring: true,
  },
  {
    id: 'arf-pet-play',
    title: 'ARF — Pet Play Dance Party',
    description: 'ARF is a pet play dance party for pups, handlers, kittens, and all pet players. Hosted by @pup_kingkobe and @thehopeman1980 with drag performances by Archer Backmore aka Pup Liko and gogo dancers. No dress code, no cover, all welcome.',
    venue: 'The Drink',
    address: '459 Church St, 2nd floor, Toronto',
    start_time: '2026-07-13T17:00:00',
    end_time: '2026-07-13T22:00:00',
    url: 'https://www.yohomo.ca/event/arf-pet-play-dance-party-2',
    source: 'yohomo.ca',
    category_slugs: ['pet-play', 'puppy', 'fetish', 'social'],
    external_id: 'yohomo-arf',
  },
  // === VERIFIED ONE-OFF / UPCOMING EVENTS ===
  {
    id: 'playground-kink-pride',
    title: 'Playground Kink 4.2: Kink Pride',
    description: 'A double decker pride season kick off party & official after party of the Hot Tease Film Festival. Celebrating kink culture\'s contribution to PRIDE. Double DJ deck sets all night with The Highland Ponies and resident Acid Burn. Light art by DUSX and Troy Strum.',
    venue: 'Ground Control',
    address: '1279 Queen St W, Toronto',
    start_time: '2026-06-26T21:00:00',
    end_time: '2026-06-27T02:45:00',
    url: 'https://lybertine.com/events/playground-kink-4-2',
    source: 'yohomo.ca',
    category_slugs: ['fetish', 'leather', 'latex', 'puppy', 'circuit', 'pride'],
    external_id: 'yohomo-playground-kink',
  },
  {
    id: 'impulse-hardwired',
    title: 'Impulse — Hardwired x Techromancy',
    description: "Impulse is one of Toronto's largest fetish party series. Known for enticing stage and circus performances, thumping Techno/Industrial soundscapes, curated dungeon, and a wide range of themes. Art, Fetish and Dance!",
    venue: 'Revival Event Venue',
    address: '783 College St, Toronto',
    start_time: '2026-05-30T21:00:00',
    end_time: '2026-05-31T03:00:00',
    url: 'https://www.eventbrite.ca/e/hardwired-x-techromancy-tickets-1984525405911',
    source: 'impulseto.com',
    category_slugs: ['bdsm', 'fetish', 'circuit'],
  },
  // Northern Bear Bash removed per Zigs
  {
    id: 'hardmode',
    title: 'Hardmode',
    description: 'An evening of beats, bass, and games. Come hang at FreePlay for some dance, drinks, arcade games, and friendly chats with local queer peoples in a mixed crowd. No dress code, but please dress as wild as you dare in a vanilla environment.',
    venue: 'Free Play',
    address: '300 College St, Toronto',
    start_time: '2026-05-29T21:00:00',
    end_time: '2026-05-30T02:00:00',
    url: 'https://www.yohomo.ca/event/hardmode',
    source: 'yohomo.ca',
    category_slugs: ['social', 'circuit'],
    external_id: 'yohomo-hardmode',
  },
  {
    id: 'supersexe-vampires-ball',
    title: 'SUPERSEXE — Vampire\'s Ball',
    description: 'SUPERSEXE presents Vampire\'s Ball. Dark, sexy, vampire-themed queer party at See-Scape.',
    venue: 'See-Scape',
    address: '347 Keele St, Toronto',
    start_time: '2026-06-07T21:00:00',
    end_time: '2026-06-08T02:00:00',
    url: 'https://www.yohomo.ca/event/supersexe-vampires-ball',
    source: 'yohomo.ca',
    category_slugs: ['goth', 'circuit', 'fetish'],
    external_id: 'yohomo-supersexe',
  },
  // === RECURRING / UNVERIFIED BUT PLAUSIBLE EVENTS ===
  {
    id: 'fetish-night-eagle',
    title: 'Fetish Night at the Eagle',
    description: 'Dress code enforced. Leather, latex, rubber, uniforms — all welcome. Dark room open.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-14T21:00:00',
    end_time: '2026-06-15T02:00:00',
    url: 'https://www.instagram.com/blackeagletoronto/',
    source: 'instagram',
    category_slugs: ['fetish', 'leather', 'bdsm'],
    recurrence: 'nth-weekday:2-6',
    recurrence_label: 'Every 2nd Saturday',
    is_recurring: true,
  },
  // Drag events removed per Zigs — only kink/fetish events
  {
    id: 'woof-bear',
    title: 'Woof Toronto — Bear Night',
    description: 'Monthly bear social. Fur, flannel, and good times. All bear-adjacent welcome.',
    venue: 'Woof',
    address: '525 Church St, Toronto',
    start_time: '2026-06-20T21:00:00',
    end_time: '2026-06-21T02:00:00',
    url: 'https://www.instagram.com/wooftoronto/',
    source: 'instagram',
    category_slugs: ['bear', 'social'],
    recurrence: 'nth-weekday:3-6',
    recurrence_label: 'Every 3rd Saturday',
    is_recurring: true,
  },
  {
    id: 'pride-main',
    title: 'Toronto Pride — Main Stage',
    description: 'Pride weekend main event! Performances, DJs, thousands of queers flooding Church St.',
    venue: 'Church & Wellesley',
    address: 'Church St & Wellesley St, Toronto',
    start_time: '2026-06-28T12:00:00',
    end_time: '2026-06-28T23:00:00',
    url: 'https://pridetoronto.com',
    source: 'pridetoronto.com',
    category_slugs: ['pride', 'circuit'],
  },
  // === PITBULL EVENTS (Source: pitbullevents.com — dates unverified beyond what's listed) ===
  {
    id: 'pitbull-bunker',
    title: 'Pitbull Bunker Take Over',
    description: "Pitbull is back for our monthly event. Great music and sexy vibes. Whether you're coming to dance, flirt, or make new friends, Pitbull always delivers.",
    venue: 'The Bunker',
    address: 'Toronto',
    start_time: '2026-06-05T22:00:00',
    end_time: '2026-06-06T03:00:00',
    url: 'https://www.pitbullevents.com/products/pitbull-at-bunker',
    source: 'pitbullevents.com',
    category_slugs: ['fetish', 'social', 'circuit'],
    recurrence: '1st-fri',
    recurrence_label: 'Every 1st Friday',
    is_recurring: true,
  },
  {
    id: 'pitbull-corruption',
    title: 'Pitbull Fetish Pride — Corruption',
    description: 'The biggest fetish party of Toronto Pride. The Opera House turns into a dark dungeon. Harness up, pup hoods on, any fetish goes. DJ TRND opens, Brian Kent headlines.',
    venue: 'The Opera House',
    address: '735 Queen St E, Toronto',
    start_time: '2026-06-26T22:00:00',
    end_time: '2026-06-27T04:00:00',
    url: 'https://www.ticketweb.ca/event/pitbull-events-presents-corruption-featuring-the-opera-house-tickets/14178414',
    source: 'pitbullevents.com',
    category_slugs: ['fetish', 'bdsm', 'leather', 'latex', 'puppy', 'pride'],
  },
  {
    id: 'pitbull-utopia',
    title: 'Pitbull Utopia — Pride Dance Party',
    description: 'The ultimate Pride celebration. Legendary DJs, stunning shows, rainbow paradise. Dance floor packed with sexy bodies all night.',
    venue: 'The Phoenix',
    address: '410 Sherbourne St, Toronto',
    start_time: '2026-06-27T22:00:00',
    end_time: '2026-06-28T04:00:00',
    url: 'https://www.pitbullevents.com/products/pitbull-pride-2026-utopia',
    source: 'pitbullevents.com',
    category_slugs: ['circuit', 'pride', 'social'],
  },
  {
    id: 'camp-boozy',
    title: 'Camp Boozy 2026',
    description: "A naughty weekend in the woods at Cedar's Campground. Two barn dance parties (Fri & Sat) with Montreal's Diskommander, pool parties, Boozy Olympics.",
    venue: "Cedar's Campground",
    address: 'Ontario',
    start_time: '2026-08-01T16:00:00',
    end_time: '2026-08-03T12:00:00',
    url: 'https://www.pitbullevents.com',
    source: 'pitbullevents.com',
    category_slugs: ['circuit', 'social', 'bear'],
  },
  // === G.L.U.E. Pup Pride — VERIFIED: June 11 (2nd Thursday) via Black Eagle vision audit ===
  {
    id: 'glue-pup-pride',
    title: 'G.L.U.E. Pup Pride',
    description: 'G.L.U.E. Pup Pride event. Celebrating pup pride and community. Pups, handlers, and allies welcome. Pup gear and pride colors encouraged.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-11T19:00:00',
    end_time: '2026-06-12T00:00:00',
    url: 'https://www.instagram.com/pupkingkobe/',
    source: 'community',
    category_slugs: ['puppy', 'pride', 'leather'],
  },
  {
    id: 'pup-romp',
    title: 'Pup Romp',
    description: "Pup Romp — Toronto's puppy play social! Pups and handlers gather for moshing, socializing, and good vibes. All experience levels welcome. Pup gear welcome but not required.",
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-08T14:00:00',
    end_time: '2026-06-08T17:00:00',
    url: '',
    source: 'community',
    category_slugs: ['puppy', 'pet-play', 'social'],
    recurrence: 'nth-weekday:2-6',
    recurrence_label: 'Every 2nd Saturday',
    is_recurring: true,
  },
  // === NEW EVENTS — 2026-05-26 SCRAPE ===
  {
    id: 'pervert-laureate',
    title: 'Pervert Laureate — Play Party for Women, Trans, 2S, NB & GNC Folx',
    description: "Kick off pride month with an evening of sensual play, kink and connection. Whether you are a seasoned kinkster or a curious newbie, you are welcome. Activities include naked tarot readings, spanking booth, wax play station, spin the bottle, simple rope demo, crafts and more. Play areas with spanking benches, massage tables, St Andrew's Crosses, hard points. Sex positive, consent-first space. Cis men not permitted.",
    venue: 'Birdhaus',
    address: '1233 Queen St W Rear, Toronto',
    start_time: '2026-06-05T20:00:00',
    end_time: '2026-06-05T23:55:00',
    url: 'https://www.yohomo.ca/event/pervert-laureate---a-play-party-for-women-trans-2-spirit-nonbinary-gender-nonconforming-folx',
    source: 'yohomo.ca',
    category_slugs: ['bdsm', 'fetish', 'workshop', 'pride'],
  },
  {
    id: 'suds-pre-pride-splash',
    title: 'SUDS — Pre-Pride Splash',
    description: "Slip inside Toronto's only full-out party inside a bathhouse. Dance party, cruising party, flirting party, and hot tub party — whatever you want it to be! Complete with a bar, custom sound, lights, and 4 floors of fun. Resident DJ Phillippe with special guest Manual Labour from Montreal. Male only (trans-men inclusive). Dress code: whatever makes you feel sexy.",
    venue: 'Spa Excess',
    address: '105 Carlton St, Toronto',
    start_time: '2026-05-29T21:00:00',
    end_time: '2026-05-30T02:00:00',
    url: 'https://www.yohomo.ca/event/suds-pre-pride-splash',
    source: 'yohomo.ca',
    category_slugs: ['cruising', 'pride', 'social'],
  },
  {
    id: 'naked-ish-pride-2026',
    title: 'NAKED-ish: Pride 2026',
    description: "Toronto's #1 gay underwear party is back just in time for Pride! Get sweaty on the dance floor in a room filled with men in their underwear (or less). House music, free clothes check, free snacks & more.",
    venue: 'Sound Machine',
    address: '178 Bathurst St, Toronto',
    start_time: '2026-06-27T22:00:00',
    end_time: '2026-06-28T04:00:00',
    url: 'https://www.yohomo.ca/event/naked-ish-pride-2026',
    source: 'yohomo.ca',
    category_slugs: ['underwear', 'pride', 'circuit'],
  },
  {
    id: 'balls-deep-disco-pride',
    title: 'Balls Deep Disco: Pride Underwear Party',
    description: "Holy underwear party Batman — we're BACK on Thursday night at Toronto Pride for our annual PRIDE UNDERWEAR PARTY! Get on your skivvies cause it's gonna be a wild one with DJ Mondonexus joining us all the way from San Francisco. Kick off pride weekend the right way.",
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-25T22:00:00',
    end_time: '2026-06-26T02:30:00',
    url: 'https://www.yohomo.ca/event/balls-deep-disco-pride-underwear-party-2',
    source: 'yohomo.ca',
    category_slugs: ['underwear', 'pride', 'fetish'],
  },
  {
    id: 'northern-bear-bash-pride',
    title: 'Northern Bear Bash: Pride',
    description: "It's Pride Saturday — and the BEARS are taking over. Northern Bear Bash returns for our biggest night of the year with BEAR PRIDE, a full-venue celebration built for the bear community and everyone who loves it. Body-positive, inclusive, and all about good energy. DJs: DJ SAMMM & Mark Falco. Go Go dancers.",
    venue: 'El Mocambo',
    address: '464 Spadina Ave, Toronto',
    start_time: '2026-06-27T21:00:00',
    end_time: '2026-06-28T03:00:00',
    url: 'https://www.yohomo.ca/event/northern-bear-bash-pride',
    source: 'yohomo.ca',
    category_slugs: ['bear', 'pride', 'social'],
  },
  {
    id: 'pervert-matinee',
    title: 'Pervert — Matinée Pride Party',
    description: "Surrender to the beauty of darkness and unleash your wildest dreams at Matinée's PERVERT. Europe's hottest party takes over Toronto Pride Weekend at REBEL main room. DJs: KARSTEN SOLLORS, IVAN GOMEZ, MOUSSA, CHEZ CALABRESE.",
    venue: 'Rebel Nightclub',
    address: '11 Polson Pier, Toronto',
    start_time: '2026-06-26T22:00:00',
    end_time: '2026-06-27T06:00:00',
    url: 'https://www.yohomo.ca/event/pervert',
    source: 'yohomo.ca',
    category_slugs: ['circuit', 'pride'],
  },
  {
    id: 'macho-pride',
    title: 'Macho Pride',
    description: "A celebration of Pride, freedom, music, & men. Music by: HARRY ROMERO, CHEZ CALABRESE, JOSH KARMIN. At Complex.",
    venue: 'Complex',
    address: '19 Toronto St, Toronto',
    start_time: '2026-06-13T22:00:00',
    end_time: '2026-06-14T04:00:00',
    url: 'https://www.yohomo.ca/event/macho-pride',
    source: 'yohomo.ca',
    category_slugs: ['circuit', 'pride'],
  },
  {
    id: 'daddy-next-door-10',
    title: 'Daddy Next Door',
    description: "Move your body with us at The Black Eagle for another fantastic night of house music, hot daddies & daddy chasers! DJ Dwayne Minard headlining with Mikey Boy on opening. Go Go dancers: Tucker, Raj, Victor & Cherry Topp.",
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-13T21:00:00',
    end_time: '2026-06-14T02:00:00',
    url: 'https://www.yohomo.ca/event/daddy-next-door-10',
    source: 'yohomo.ca',
    category_slugs: ['bear', 'social'],
  },
  {
    id: 'house-boy-pride-warmup',
    title: 'House Boy: Pride Warmup',
    description: "PRISM PRIDE WARMUP EVENT! HOUSEBOY at BUNKER on JUNE 12 — a celebration! Special guest DJ MADAM LOLA plus KENNY GLASG. Pride warmup circuit party at Bunker.",
    venue: 'Bunker',
    address: '489 Church St, Toronto',
    start_time: '2026-06-12T22:00:00',
    end_time: '2026-06-13T05:00:00',
    url: 'https://www.yohomo.ca/event/house-boy-pride-warmup',
    source: 'yohomo.ca',
    category_slugs: ['circuit', 'pride'],
  },
  {
    id: 'phillippe-sissy',
    title: 'Phillippe Presents: SISSY',
    description: "Sissy is strutting into Buddies for a full-building invasion on Pride Thursday! A multi-room, all-Toronto headliner lineup of Toronto's greatest and gayest DJs and performers. Strap on something very cute and prepare to dance.",
    venue: 'Buddies in Bad Times',
    address: '12 Alexander St, Toronto',
    start_time: '2026-06-25T21:00:00',
    end_time: '2026-06-26T02:30:00',
    url: 'https://www.yohomo.ca/event/phillippepresentssissy',
    source: 'yohomo.ca',
    category_slugs: ['circuit', 'pride'],
  },
  {
    id: 'cnsred-vol2-pride',
    title: 'CNSRED VOL.2 — Pride Edition',
    description: "A Berlin-inspired underground techno event where the music runs deep, the lights stay low, and the focus is on the sound. No phones. No cameras. No distractions. Hypnotic techno and driving house rhythms. At Bunker.",
    venue: 'Bunker',
    address: '489 Church St, Toronto',
    start_time: '2026-06-24T22:00:00',
    end_time: '2026-06-25T03:00:00',
    url: 'https://www.yohomo.ca/event/cnsred-vol-2-pride-edition',
    source: 'yohomo.ca',
    category_slugs: ['circuit', 'social'],
  },
  // === NEW EVENTS — 2026-05-26 WEEKLY VISION SCRAPE ===
  // BLUF Toronto regular monthly (non-Pride)
  {
    id: 'bluf-toronto-monthly',
    title: 'BLUF Toronto — Leather Social',
    description: 'BLUF (Brotherhood of Leather Uniforms) Toronto Leather Social on the last Saturday of the month. Come out in your leather and uniforms to meet fellow BLUF members and other leathermen. No dress code enforced. Open to non-members. No cover.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-05-30T18:00:00',
    end_time: '2026-05-30T20:30:00',
    url: 'https://www.bluf.com/events/',
    source: 'bluf.com',
    category_slugs: ['leather', 'bluf', 'social'],
    recurrence: 'nth-weekday:5-6',
    recurrence_label: 'Last Saturday of the month',
    is_recurring: true,
  },
  // Black Eagle recurring events (source: blackeagletoronto.com, vision-verified 2026-05-26)
  {
    id: 'kink-101',
    title: 'KINK 101 — Intro to BDSM and Kink for Beginners',
    description: 'Intro to BDSM and Kink for Beginners. Hosted by Jeremy Feist. A welcoming workshop for those new to kink. Learn the basics in a safe, no-pressure environment. 1st Thursday of the month. No cover.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-04T21:00:00',
    end_time: '2026-06-05T00:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['bdsm', 'workshop', 'fetish'],
    recurrence: 'nth-weekday:1-4',
    recurrence_label: 'Every 1st Thursday',
    is_recurring: true,
  },
  {
    id: 'jockstrap-eagle',
    title: 'JOCKSTRAP',
    description: 'Jockstrap night at the Eagle. Jockstrap attire optional. Clothes check onsite. Men only. 1st Saturday of the month.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-06T21:00:00',
    end_time: '2026-06-07T02:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['underwear', 'fetish'],
    recurrence: 'nth-weekday:1-6',
    recurrence_label: 'Every 1st Saturday',
    is_recurring: true,
  },
  {
    id: 'glue-social',
    title: 'G.L.U.E. — Gear & Leather Untied Event',
    description: 'G.L.U.E. — A Gear & Leather Untied Event. An evening of social, play and gear night. 7PM social, 8PM play. 2nd Thursday of the month. No cover.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-11T19:00:00',
    end_time: '2026-06-12T00:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['leather', 'bdsm', 'fetish', 'social'],
    recurrence: 'nth-weekday:2-4',
    recurrence_label: 'Every 2nd Thursday',
    is_recurring: true,
  },
  {
    id: 'lock-chastity',
    title: 'L.O.C.K. — Lovers of Chastity & Kink',
    description: 'L.O.C.K. (Lovers of Chastity & Kink) chastity social. Keyholders and newcomers welcome. Every 3rd Wednesday of the month. No cover.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-17T20:00:00',
    end_time: '2026-06-18T00:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['bdsm', 'fetish', 'social'],
    recurrence: 'nth-weekday:3-3',
    recurrence_label: 'Every 3rd Wednesday',
    is_recurring: true,
  },
  {
    id: 'naked-night',
    title: 'NAKED NIGHT',
    description: 'Nudity mandatory on main floor. Clothes-check: $6. 3rd Thursday of the month.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-18T21:00:00',
    end_time: '2026-06-19T02:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['cruising', 'fetish'],
    recurrence: 'nth-weekday:3-4',
    recurrence_label: 'Every 3rd Thursday',
    is_recurring: true,
  },
  {
    id: 'dfmo',
    title: 'D.F.M.O. — Dance Floor Makeout',
    description: 'Dance Floor Makeout. Hosted by David Kraft. Every 3rd Friday of the month. Resident DJ John Caffery & special guests.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-19T21:00:00',
    end_time: '2026-06-20T02:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['social', 'fetish'],
    recurrence: 'nth-weekday:3-5',
    recurrence_label: 'Every 3rd Friday',
    is_recurring: true,
  },
  {
    id: 'erotic-life-drawing',
    title: 'Erotic Life Drawing',
    description: 'Live models in erotic poses. Bring your own pencils/ink/paper. 2nd Saturday of the month. No cover.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-13T16:00:00',
    end_time: '2026-06-13T19:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['workshop', 'fetish'],
    recurrence: 'nth-weekday:2-6',
    recurrence_label: 'Every 2nd Saturday',
    is_recurring: true,
  },
  {
    id: 'surrv-leather-dark-room',
    title: "SURRV'D — Leather Dark Room T-Dance",
    description: "SURRV'D leather dark room T-dance. DJ Relentless. 2nd Sunday of the month. Free entry.",
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-14T16:00:00',
    end_time: '2026-06-14T20:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['leather', 'cruising', 'social'],
    recurrence: 'nth-weekday:2-7',
    recurrence_label: 'Every 2nd Sunday',
    is_recurring: true,
  },
  {
    id: 'wanker',
    title: 'WANKER',
    description: 'Wanker — 1st & 4th Wednesday jack-off event. Starts 8pm to close. Men only.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-04T20:00:00',
    end_time: '2026-06-05T03:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['cruising', 'fetish'],
    recurrence: '1st-and-4th-wed',
    recurrence_label: '1st & 4th Wednesday',
    is_recurring: true,
  },
  {
    id: 'pup-pride',
    title: 'Pup Pride',
    description: 'Pup Pride night at the Black Eagle. Details TBA. Celebrating pup pride during Pride week.',
    venue: 'The Black Eagle',
    address: '457 Church St, Toronto',
    start_time: '2026-06-24T19:00:00',
    end_time: '2026-06-25T00:00:00',
    url: 'https://www.blackeagletoronto.com/',
    source: 'blackeagletoronto.com',
    category_slugs: ['puppy', 'pride', 'fetish'],
  },
  // Eventbrite-sourced events
  {
    id: 'hot-tease-film-fest',
    title: 'Hot Tease Film Festival & Award Show',
    description: 'Hot Tease XXX Film Fest: Bold adult films, themed drinks, live performances, & a cash prize for the audience voted "Top Tease"! Organized by The Tea & Kink Social.',
    venue: 'Super Wonder Gallery',
    address: '1162 Bloor Street West, Toronto',
    start_time: '2026-06-06T19:00:00',
    end_time: '2026-06-06T23:30:00',
    url: 'https://www.eventbrite.ca/e/hot-tease-film-festival-award-show-tickets-1982408181235',
    source: 'eventbrite.ca',
    category_slugs: ['fetish', 'bdsm', 'pride'],
  },
  {
    id: 'kiss-kink-tantra',
    title: 'K.I.S.S. — Kink/Tantra Instruction & Social Salon',
    description: 'A Kink–Tantra Social Salon for connection, skill, and embodied exploration. Topic: SACRED KINK: THE 4 PATHWAYS — Protocol, Service, Ritual, and Worship. Eat, chat, learn, play. 2nd Thursday & 4th Saturday of the month.',
    venue: 'Studio 202, 43 Towns Rd',
    address: '43 Towns Rd, Etobicoke, Toronto',
    start_time: '2026-06-11T18:30:00',
    end_time: '2026-06-11T21:30:00',
    url: 'https://www.eventbrite.ca/e/kiss-kinktantra-instruction-social-salon-jun-11-tickets-1989884401812',
    source: 'eventbrite.ca',
    category_slugs: ['bdsm', 'workshop', 'fetish'],
    recurrence: '2nd-thu-and-4th-sat',
    recurrence_label: '2nd Thursday & 4th Saturday',
    is_recurring: true,
  },
  {
    id: 'fetnoir-back-to-school',
    title: 'fetNOIR: Back To School — Play & Dance Party',
    description: 'fetNOIR is back in session! Back To School themed fetish play and dance party. 7 custom pieces of fetish equipment, dungeon play area with dungeon master, photo booth, go-go dancers. Dress code: Fetish Wear, Leather, Lace, PVC, Goth, Lingerie, Rubber. No streetwear. DJ Lazarus (electro, EBM, darkwave, techno, house).',
    venue: 'Ground Control',
    address: '1279 Queen St W, Toronto',
    start_time: '2026-08-08T21:00:00',
    end_time: '2026-08-09T02:30:00',
    url: 'https://www.eventbrite.ca/e/fetnoir-back-to-school-theme-play-dance-party-tickets-1985802561919',
    source: 'eventbrite.ca',
    category_slugs: ['bdsm', 'fetish', 'goth', 'circuit'],
  },
  // Lybertine-sourced event
  {
    id: 'mall-goths',
    title: 'Mall Goths — 90s and Y2K Goth Dance Party',
    description: "A 90s and Y2K goth dance party. Spin the darkest hits of the mall goth era — Marilyn Manson, Nine Inch Nails, The Cure, Depeche Mode, Sisters of Mercy and more. Dark vibes, fog machines, and all-black everything.",
    venue: 'Ground Control',
    address: '1279 Queen St W, Toronto',
    start_time: '2026-07-03T21:00:00',
    end_time: '2026-07-04T02:00:00',
    url: 'https://lybertine.com/events/mall-goths-90s-and-y2k-goth-dance-party',
    source: 'lybertine.com',
    category_slugs: ['goth', 'circuit'],
  },
];