// Static seed data for Vercel deployment
// This file contains all events as static JSON so the site works without a database
// The admin/submission features will need a Turso DB for production writes

export interface Event {
  id: string;
  title: string;
  description: string;
  venue: string;
  address: string;
  start_time: string;
  end_time: string;
  url: string;
  source: string;
  category_slugs: string[];
  recurrence?: string;
  recurrence_label?: string;
  is_recurring?: boolean;
  external_id?: string;
}

export interface Category {
  slug: string;
  name: string;
  emoji: string;
  color: string;
  description: string;
}

export const categories: Category[] = [
  { slug: 'circuit', name: 'Circuit Party', emoji: '🔊', color: '#E11D48', description: 'Circuit parties, dance events, big beats' },
  { slug: 'leather', name: 'Leather', emoji: '🧥', color: '#1E1E1E', description: 'Leather events, leather bars, leather contests' },
  { slug: 'latex', name: 'Latex / Rubber', emoji: '🖤', color: '#0EA5E9', description: 'Latex and rubber events, dress codes' },
  { slug: 'bdsm', name: 'BDSM / Kink', emoji: '⛓️', color: '#7C3AED', description: 'BDSM demos, munches, play parties, workshops' },
  { slug: 'puppy', name: 'Puppy Play', emoji: '🐕', color: '#F59E0B', description: 'Puppy play events, moshes, socials' },
  { slug: 'furry', name: 'Furry', emoji: '🐾', color: '#10B981', description: 'Furry meetups, socials, events' },
  { slug: 'drag', name: 'Drag', emoji: '💄', color: '#EC4899', description: 'Drag shows, drag queen events, drag king nights' },
  { slug: 'bear', name: 'Bear', emoji: '🐻', color: '#92400E', description: 'Bear events, bear socials, bear runs' },
  { slug: 'fetish', name: 'Fetish Night', emoji: '🔥', color: '#DC2626', description: 'General fetish nights, dress-code parties' },
  { slug: 'underwear', name: 'Underwear', emoji: '🩲', color: '#6366F1', description: 'Underwear parties, underwear nights' },
  { slug: 'cruising', name: 'Cruising', emoji: '👀', color: '#059669', description: 'Cruising events, dark rooms, saunas' },
  { slug: 'social', name: 'Social / Mixer', emoji: '🍻', color: '#6B7280', description: 'Social events, meetups, mixers, brunches' },
  { slug: 'workshop', name: 'Workshop / Education', emoji: '📚', color: '#8B5CF6', description: 'Educational workshops, skill-sharing, demos' },
  { slug: 'pride', name: 'Pride', emoji: '🌈', color: '#F43F5E', description: 'Pride events, pride month activities' },
  { slug: 'pet-play', name: 'Pet Play', emoji: '🐾', color: '#D97706', description: 'Pet play, puppy, kitten, pony play events' },
  { slug: 'bluf', name: 'BLUF', emoji: '🔵', color: '#2563EB', description: 'BLUF (Brotherhood of Leather Uniforms) events' },
  { slug: 'goth', name: 'Goth / Dark', emoji: '🦇', color: '#4A0E4E', description: 'Goth, dark alternative, industrial events' },
];

export const events: Event[] = [
  // === KEY RECURRING EVENTS ===
  {
    id: 'bad-dog',
    title: 'Bad Dog',
    description: 'Bad Dog — the legendary pup & handler party at The Black Eagle. Pups, handlers, and dog lovers unite. Dress code: pup gear encouraged. Dark room open.',
    venue: 'The Black Eagle',
    address: '718 Queen St W, Toronto',
    start_time: '2026-06-06T21:00:00',
    end_time: '2026-06-07T02:00:00',
    url: 'https://www.getmuzzled.ca',
    source: 'getmuzzled.ca',
    category_slugs: ['puppy', 'fetish'],
    recurrence: 'nth-weekday:1-6',
    recurrence_label: 'Every 1st Saturday',
    is_recurring: true,
  },
  {
    id: 'bluf-toronto',
    title: 'BLUF Toronto',
    description: 'BLUF (Brotherhood of Leather Uniforms) Toronto meetup. Leather and uniform dress code enforced. A night for men who appreciate leather, uniforms, and the culture around them.',
    venue: 'The Black Eagle',
    address: '718 Queen St W, Toronto',
    start_time: '2026-06-19T20:00:00',
    end_time: '2026-06-19T23:00:00',
    url: 'https://www.bluf.com',
    source: 'bluf.com',
    category_slugs: ['leather', 'bluf'],
    recurrence: 'nth-weekday:3-5',
    recurrence_label: 'Every 3rd Friday',
    is_recurring: true,
  },
  {
    id: 'glue-pup-pride',
    title: 'G.L.U.E. Pup Pride',
    description: 'G.L.U.E. (Gay Leather Uniform Exchange) Pup Pride event. Celebrating pup pride and community. Pups, handlers, and allies welcome. Pup gear and pride colors encouraged.',
    venue: 'The Black Eagle',
    address: '718 Queen St W, Toronto',
    start_time: '2026-06-14T14:00:00',
    end_time: '2026-06-14T18:00:00',
    url: '',
    source: 'getmuzzled.ca',
    category_slugs: ['puppy', 'pride', 'leather'],
  },
  {
    id: 'pup-romp',
    title: 'Pup Romp',
    description: "Pup Romp — Toronto's puppy play social! Pups and handlers gather for moshing, socializing, and good vibes. All experience levels welcome. Pup gear welcome but not required.",
    venue: 'The Black Eagle',
    address: '718 Queen St W, Toronto',
    start_time: '2026-06-08T14:00:00',
    end_time: '2026-06-08T17:00:00',
    url: '',
    source: 'community',
    category_slugs: ['puppy', 'pet-play', 'social'],
    recurrence: 'nth-weekday:2-6',
    recurrence_label: 'Every 2nd Saturday',
    is_recurring: true,
  },
  {
    id: 'muzzled',
    title: 'MUZZLED',
    description: 'MUZZLED is where the party animals go. Queer, kink-friendly, community-focused events. Great music, great vibes, great people. Be unapologetically yourself.',
    venue: 'The Parkdale Hall',
    address: '1605 Queen St E Suite 3, Toronto',
    start_time: '2026-06-07T21:00:00',
    end_time: '2026-06-08T02:00:00',
    url: 'https://www.getmuzzled.ca',
    source: 'getmuzzled.ca',
    category_slugs: ['puppy', 'fetish', 'social'],
    recurrence: 'nth-weekday:1-6',
    recurrence_label: 'Monthly (check site)',
    is_recurring: true,
  },
  {
    id: 'arf-pet-play',
    title: 'ARF — Pet Play Dance Party',
    description: 'ARF is a pet play dance party for pups, handlers, kittens, and all pet players. Dance, socialize, and play. Pet gear welcome. Inclusive and kink-friendly space.',
    venue: 'The Black Eagle',
    address: '718 Queen St W, Toronto',
    start_time: '2026-06-27T21:00:00',
    end_time: '2026-06-28T02:00:00',
    url: 'https://www.yohomo.ca/event/arf-pet-play-dance-party-2',
    source: 'yohomo.ca',
    category_slugs: ['pet-play', 'puppy', 'fetish'],
    external_id: 'yohomo-arf',
  },
  // === OTHER TORONTO EVENTS ===
  {
    id: 'crank',
    title: 'Crank — Circuit Party',
    description: "Toronto's hottest circuit party. 300+ guys, world-class DJs, insane lights.",
    venue: 'Fly 2.0',
    address: '6 Gloucester St, Toronto',
    start_time: '2026-06-06T22:00:00',
    end_time: '2026-06-07T04:00:00',
    url: 'https://flynightclub.com',
    source: '',
    category_slugs: ['circuit'],
  },
  {
    id: 'fetish-night-eagle',
    title: 'Fetish Night at the Eagle',
    description: 'Dress code enforced. Leather, latex, rubber, uniforms — all welcome. Dark room open.',
    venue: 'The Black Eagle',
    address: '718 Queen St W, Toronto',
    start_time: '2026-06-13T21:00:00',
    end_time: '2026-06-14T02:00:00',
    url: '',
    source: '',
    category_slugs: ['fetish', 'leather', 'bdsm'],
    recurrence: 'nth-weekday:2-6',
    recurrence_label: 'Every 2nd Saturday',
    is_recurring: true,
  },
  {
    id: 'drag-brunch',
    title: 'Drag Brunch — Sunday Fierce',
    description: "Mimosa-fueled drag brunch with Toronto's best queens. Reservations recommended.",
    venue: 'Crews & Tangos',
    address: '508 Church St, Toronto',
    start_time: '2026-06-14T11:00:00',
    end_time: '2026-06-14T14:00:00',
    url: '',
    source: '',
    category_slugs: ['drag', 'social'],
    recurrence: 'weekly:0',
    recurrence_label: 'Every Sunday',
    is_recurring: true,
  },
  {
    id: 'leather-latex-social',
    title: 'Leather & Latex Social',
    description: 'Casual social for the leather and latex community. No play, just vibes and connections.',
    venue: 'The Zipperz',
    address: '72 Carlton St, Toronto',
    start_time: '2026-06-15T19:00:00',
    end_time: '2026-06-15T22:00:00',
    url: '',
    source: '',
    category_slugs: ['leather', 'latex', 'social'],
  },
  {
    id: 'bdsm-101',
    title: 'BDSM 101 Workshop',
    description: 'Beginner-friendly workshop covering safety, negotiation, and basic rope/bondage techniques. Demo + hands-on practice.',
    venue: 'Come As You Are',
    address: '701B Queen St W, Toronto',
    start_time: '2026-06-18T19:00:00',
    end_time: '2026-06-18T21:00:00',
    url: '',
    source: '',
    category_slugs: ['bdsm', 'workshop'],
  },
  {
    id: 'woof-bear',
    title: 'Woof Toronto — Bear Night',
    description: 'Monthly bear social. Fur, flannel, and good times. All bear-adjacent welcome.',
    venue: 'Woof',
    address: '525 Church St, Toronto',
    start_time: '2026-06-20T21:00:00',
    end_time: '2026-06-21T02:00:00',
    url: '',
    source: '',
    category_slugs: ['bear', 'social'],
    recurrence: 'nth-weekday:3-6',
    recurrence_label: 'Every 3rd Saturday',
    is_recurring: true,
  },
  {
    id: 'furry-meetup',
    title: 'Furry Meetup TO',
    description: 'Casual furry meetup — fursuits welcome but not required. Art share, socializing, snacks.',
    venue: 'Glad Day Bookshop',
    address: '499 Church St, Toronto',
    start_time: '2026-06-22T15:00:00',
    end_time: '2026-06-22T18:00:00',
    url: '',
    source: '',
    category_slugs: ['furry', 'social'],
  },
  {
    id: 'pride-fetish-ball',
    title: 'Pride Fetish Ball',
    description: 'The annual Pride Fetish Ball. Dress to impress. Leather, latex, rubber, pups — the works.',
    venue: 'The Black Eagle',
    address: '718 Queen St W, Toronto',
    start_time: '2026-06-27T22:00:00',
    end_time: '2026-06-28T03:00:00',
    url: '',
    source: '',
    category_slugs: ['fetish', 'leather', 'latex', 'puppy', 'bdsm'],
  },
  {
    id: 'pride-main',
    title: 'Toronto Pride — Main Stage',
    description: 'Pride weekend main event! Performances, DJs, thousands of queers flooding Church St.',
    venue: 'Church & Wellesley',
    address: 'Church St & Wellesley St, Toronto',
    start_time: '2026-06-28T12:00:00',
    end_time: '2026-06-28T23:00:00',
    url: 'https://pridetoronto.com',
    source: '',
    category_slugs: ['pride', 'circuit', 'drag'],
  },
  {
    id: 'underwear-skivvies',
    title: 'Underwear Party — Skivvies',
    description: 'Underwear-only dance party. Check your pants at the door.',
    venue: 'Fly 2.0',
    address: '6 Gloucester St, Toronto',
    start_time: '2026-07-04T22:00:00',
    end_time: '2026-07-05T04:00:00',
    url: '',
    source: '',
    category_slugs: ['underwear', 'circuit'],
  },
  {
    id: 'rope-bondage-201',
    title: 'Rope Bondage Intermediate Workshop',
    description: 'Building on 101 — suspension prep, chest harnesses, and flow. Must have attended 101 or have experience.',
    venue: 'Come As You Are',
    address: '701B Queen St W, Toronto',
    start_time: '2026-07-09T19:00:00',
    end_time: '2026-07-09T21:30:00',
    url: '',
    source: '',
    category_slugs: ['bdsm', 'workshop'],
  },
  // === SOURCE EVENTS ===
  {
    id: 'rubber-sluts-gimp',
    title: 'Rubber Sluts: GIMP',
    description: "Rubber Sluts presents GIMP — Slick N' Shiny Rubber and Latex Play Party. Celebrating rubber and latex dress up, full coverage suits, everyone from the latex curious to the seasoned rubberist!",
    venue: 'Toronto Goth Events venue',
    address: 'Toronto',
    start_time: '2026-06-14T22:00:00',
    end_time: '2026-06-15T03:00:00',
    url: 'https://www.torontogothevents.com/events/rubber-sluts-gimp/',
    source: 'torontogothevents.com',
    category_slugs: ['latex', 'bdsm', 'fetish', 'goth'],
  },
  // YUSSUR removed: was Jan 10 2026, already past. No future date confirmed.
  {
    id: 'pitbull-bunker',
    title: 'Pitbull Bunker Take Over',
    description: "Pitbull is back for our monthly event. Great music and sexy vibes. Whether you're coming to dance, flirt, or make new friends, Pitbull always delivers.",
    venue: 'The Bunker',
    address: 'Toronto',
    start_time: '2026-06-21T22:00:00',
    end_time: '2026-06-22T03:00:00',
    url: 'https://www.pitbullevents.com',
    source: 'pitbullevents.com',
    category_slugs: ['fetish', 'social', 'circuit'],
    recurrence: 'monthly:21',
    recurrence_label: 'Monthly',
    is_recurring: true,
  },
  {
    id: 'pitbull-corruption',
    title: 'Pitbull Fetish Pride — Corruption',
    description: 'The biggest fetish party of Toronto Pride. The Opera House turns into a dark dungeon. Harness up, pup hoods on, any fetish goes. DJ TRND opens, Brian Kent headlines.',
    venue: 'The Opera House',
    address: '735 Queen St E, Toronto',
    start_time: '2026-06-28T22:00:00',
    end_time: '2026-06-29T04:00:00',
    url: 'https://www.pitbullevents.com',
    source: 'pitbullevents.com',
    category_slugs: ['fetish', 'bdsm', 'leather', 'latex', 'puppy', 'pride'],
  },
  {
    id: 'pitbull-utopia',
    title: 'Pitbull Utopia — Pride Dance Party',
    description: 'The ultimate Pride celebration. Legendary DJs, stunning shows, rainbow paradise. Dance floor packed with sexy bodies all night.',
    venue: 'The Phoenix',
    address: '410 Sherbourne St, Toronto',
    start_time: '2026-06-29T22:00:00',
    end_time: '2026-06-30T04:00:00',
    url: 'https://www.pitbullevents.com',
    source: 'pitbullevents.com',
    category_slugs: ['circuit', 'pride', 'social'],
  },
  {
    id: 'camp-boozy',
    title: 'Camp Boozy 2026',
    description: "A naughty weekend in the woods at Cedar's Campground. Two barn dance parties (Fri & Sat) with Montreal's Diskommander, pool parties, Boozy Olympics.",
    venue: "Cedar's Campground",
    address: 'Ontario',
    start_time: '2026-08-01T16:00:00',
    end_time: '2026-08-03T12:00:00',
    url: 'https://www.pitbullevents.com',
    source: 'pitbullevents.com',
    category_slugs: ['circuit', 'social', 'bear'],
  },
  {
    id: 'impulse-hardwired',
    title: 'Impulse — Hardwired x Techromancy',
    description: "Impulse is one of Toronto's largest fetish party series. Known for enticing stage and circus performances, thumping Techno/Industrial soundscapes, curated dungeon, and a wide range of themes. Art, Fetish and Dance!",
    venue: 'Toronto',
    address: 'Toronto',
    start_time: '2026-05-30T21:00:00',
    end_time: '2026-05-31T04:00:00',
    url: 'https://www.eventbrite.ca/e/hardwired-x-techromancy-tickets-1984525405911',
    source: 'impulseto.com',
    category_slugs: ['bdsm', 'fetish', 'circuit'],
  },
  {
    id: 'playground-toronto',
    title: 'PLAYGROUND Toronto',
    description: "Montreal's PLAYGROUND comes to Toronto! Leather, rubber, sports gear, drag, kink, bears, pups — every body and every fantasy. DJ Dwayne Minard on decks. Co-presented by Bear It, Pitbull!, Pup Canada, and Buddies in Bad Times Theatre.",
    venue: 'Toronto',
    address: 'Toronto',
    start_time: '2026-12-06T22:00:00',
    end_time: '2026-12-07T04:00:00',
    url: 'https://www.yohomo.ca/event/playground',
    source: 'yohomo.ca',
    category_slugs: ['leather', 'latex', 'puppy', 'bdsm', 'fetish', 'bear'],
  },
  // NOTE: Playground was originally Dec 2025, moved to Dec 2026 as likely annual
];